#!/bin/bash

cd $(dirname $0)/..

. ./scripts/version.sh

ROOT_VERSION=v0.5.0-rc1.1
TRAEFIK_VERSION=v8.2.1
CHARTS_DIR=build/static/charts

mkdir -p ${CHARTS_DIR}

curl --compressed -sfL https://github.com/knovus/k3s-root/releases/download/${ROOT_VERSION}/k3s-root-${ARCH}.tar | tar xf -
ln -sf pigz bin/unpigz
for target in iptables iptables-save iptables-restore ip6tables ip6tables-save ip6tables-restore; do
  ln -sf xtables-legacy-multi bin/$target
done
mkdir -p bin/aux && rm bin/mount && ln -sf ../busybox bin/aux/mount

TRAEFIK_FILE=traefik-${TRAEFIK_VERSION}.tgz
curl -sfL https://github.com/knovus/traefik-helm-chart/releases/download/${TRAEFIK_VERSION}/traefik-chart.tgz -o ${CHARTS_DIR}/${TRAEFIK_FILE}

cp scripts/wg-add.sh bin/aux/
